/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jalac9997
 */
public class AlienMoney extends javax.swing.JFrame {

    /**
     * Creates new form AlienMoney
     */
    public AlienMoney() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        inputLabel = new javax.swing.JLabel();
        clickwickOutput = new javax.swing.JTextField();
        drobzitLabel = new javax.swing.JLabel();
        clickwickLabel = new javax.swing.JLabel();
        drobzitOutput = new javax.swing.JTextField();
        gazoontightLabel = new javax.swing.JLabel();
        vrobitField = new javax.swing.JTextField();
        gazoontightOutput = new javax.swing.JTextField();
        frazointOutput = new javax.swing.JTextField();
        frazointLabel = new javax.swing.JLabel();
        blointointLabel = new javax.swing.JLabel();
        blointointOutput = new javax.swing.JTextField();
        vrobitLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 204));

        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        inputLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputLabel.setText("# Of Vrobits");

        clickwickOutput.setEditable(false);
        clickwickOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickwickOutputActionPerformed(evt);
            }
        });

        drobzitLabel.setText("# Of Drobzit");

        clickwickLabel.setText("# Of Clickwick");

        drobzitOutput.setEditable(false);
        drobzitOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drobzitOutputActionPerformed(evt);
            }
        });

        gazoontightLabel.setText("# Of Gazoontight");

        vrobitField.setEditable(false);
        vrobitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrobitFieldActionPerformed(evt);
            }
        });

        gazoontightOutput.setEditable(false);
        gazoontightOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gazoontightOutputActionPerformed(evt);
            }
        });

        frazointOutput.setEditable(false);
        frazointOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frazointOutputActionPerformed(evt);
            }
        });

        frazointLabel.setText("# Of Frazoint");

        blointointLabel.setText("# Of Blointoint");

        blointointOutput.setEditable(false);
        blointointOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blointointOutputActionPerformed(evt);
            }
        });

        vrobitLabel.setText("# Of Vrobit");

        startButton.setText("Confirm");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gazoontightLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clickwickLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(frazointLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(blointointLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vrobitLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addComponent(startButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(drobzitLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frazointOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drobzitOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clickwickOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vrobitField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gazoontightOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blointointOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(inputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(204, Short.MAX_VALUE))))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startButton))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drobzitOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drobzitLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clickwickOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clickwickLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gazoontightLabel)
                    .addComponent(gazoontightOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frazointOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frazointLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blointointLabel)
                    .addComponent(blointointOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrobitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vrobitLabel))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    private void clickwickOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickwickOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clickwickOutputActionPerformed

    private void drobzitOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drobzitOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drobzitOutputActionPerformed

    private void vrobitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrobitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vrobitFieldActionPerformed

    private void gazoontightOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gazoontightOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gazoontightOutputActionPerformed

    private void frazointOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frazointOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frazointOutputActionPerformed

    private void blointointOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blointointOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blointointOutputActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // WHERE ALL THE CODE WILL BE //////////////////////////////////////////////////////////////////
        
        //Variables
        double vrobitsNum = Double.parseDouble(inputField.getText());
        double drobzitsNum = 0;
        double clickwicksNum = 0;
        double gazoontightsNum = 0;
        double frazointsNum = 0;
        double blointointsNum = 0;
        
        //Constants
        final double DROBZIT = 100000;
        final double CLICKWICK = 50000;
        final double GAZOONTIGHT = 10000;
        final double FRAZOINT = 1000;
        final double BLOINTOINT = 500;
        
        //Drobzit Loop
        while (vrobitsNum > 0) {
            vrobitsNum = vrobitsNum - DROBZIT;
            drobzitsNum = drobzitsNum + 1;
        }
        vrobitsNum = vrobitsNum + DROBZIT;
        drobzitsNum = drobzitsNum - 1;
        drobzitOutput.setText(""+drobzitsNum);
        
        //Clickwick Loop
        while (vrobitsNum > 0) {
            vrobitsNum = vrobitsNum - CLICKWICK;
            clickwicksNum = clickwicksNum + 1;
        }
        vrobitsNum = vrobitsNum + CLICKWICK;
        clickwicksNum = clickwicksNum - 1;
        clickwickOutput.setText(""+clickwicksNum);
        
        //Gazoontight Loop
        while (vrobitsNum > 0) {
            vrobitsNum = vrobitsNum - GAZOONTIGHT;
            gazoontightsNum = gazoontightsNum + 1;
        }
        vrobitsNum = vrobitsNum + GAZOONTIGHT;
        gazoontightsNum = gazoontightsNum - 1;
        gazoontightOutput.setText(""+gazoontightsNum);
        
        //Frazoint Loop
        while (vrobitsNum > 0) {
            vrobitsNum = vrobitsNum - FRAZOINT;
            frazointsNum = frazointsNum + 1;
        }
        vrobitsNum = vrobitsNum + FRAZOINT;
        frazointsNum = frazointsNum - 1;
        clickwickOutput.setText(""+frazointsNum);
        
        //Blointoint Loop
        while (vrobitsNum > 0) {
            vrobitsNum = vrobitsNum - BLOINTOINT;
            blointointsNum = blointointsNum + 1;
        }
        vrobitsNum = vrobitsNum + BLOINTOINT;
        blointointsNum = blointointsNum - 1;
        clickwickOutput.setText(""+blointointsNum);
        
        //Vorbits
        clickwickOutput.setText(""+vrobitsNum);
        
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlienMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlienMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlienMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlienMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlienMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel blointointLabel;
    private javax.swing.JTextField blointointOutput;
    private javax.swing.JLabel clickwickLabel;
    private javax.swing.JTextField clickwickOutput;
    private javax.swing.JLabel drobzitLabel;
    private javax.swing.JTextField drobzitOutput;
    private javax.swing.JLabel frazointLabel;
    private javax.swing.JTextField frazointOutput;
    private javax.swing.JLabel gazoontightLabel;
    private javax.swing.JTextField gazoontightOutput;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField vrobitField;
    private javax.swing.JLabel vrobitLabel;
    // End of variables declaration//GEN-END:variables
}
